version: "3.9"
services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=simple_bank
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d simple_bank" ]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:123456@postgres:5432/simple_bank?sslmode=disable
      - GIN_MODE=release
    depends_on:
      postgres:
        condition: service_healthy
